apiVersion: v1
kind: Secret
metadata:
  name: speech-dataset-secrets
  namespace: dev  # Plassert i dev namespace
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "din_access_key_her"
  AWS_SECRET_ACCESS_KEY: "din_secret_key_her"
  S3_ENDPOINT_URL: "https://din-ceph-url.com"
  S3_BUCKET: "ml-data"
  HF_TOKEN: "din_huggingface_token_her"
